# Generated by Django 6.1 on 2026-08-13 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_tag_note_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('resource_type', models.CharField(choices=[('ARTICLE', 'Article'), ('VIDEO', 'Video'), ('DOCUMENTATION', 'Documentation'), ('GITHUB', 'Github'), ('COURSE', 'Course'), ('OTHERS', 'Others')], default='OTHER', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='notes.note')),
            ],
        ),
    ]
