# Generated by Django 6.1 on 2026-08-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('LEARNING', 'Learning'), ('LEARNED', 'Learned'), ('REVIEW', 'Review')], default='LEARNING', max_length=100),
        ),
    ]
