# Generated by Django 6.1 on 2026-08-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_note_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
