# Generated by Django 6.1 on 2026-08-17 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_rename_note_is_favourite_to_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('ARTICLE', 'Article'), ('VIDEO', 'Video'), ('DOCUMENTATION', 'Documentation'), ('GITHUB', 'Github'), ('COURSE', 'Course'), ('OTHERS', 'Others')], default='OTHERS', max_length=100),
        ),
        migrations.CreateModel(
            name='CodeSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('code', models.TextField()),
                ('language', models.CharField(choices=[('PYTHON', 'Python'), ('JAVASCRIPT', 'JavaScript'), ('TYPESCRIPT', 'TypeScript'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('SQL', 'SQL'), ('BASH', 'Bash'), ('JSON', 'JSON'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_snippets', to='notes.note')),
            ],
        ),
    ]
